# Set version of docker compose syntax, use most recent where possible
version: '3'

# Define services which will become separate containers,
# sharing a single network with DNS resolvable hostnames
services:
  # Mongo DB
  mongo:
    image: "mongo:4"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  # Mongo management console
  mongo-express:
    image: "mongo-express:0.49"
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - "mongo"
  # Elasticsearch
  elasticsearch:
    image: "elasticsearch:7.3.1"
  # Graylog log aggregator
  graylog:
    image: "graylog:3"
    ports:
      - 8002:9000
